name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  call-test-did-finder:
    uses: ./.github/workflows/tests/test-did-finder-python.yaml
  call-deploy-did-finder:
    needs: call-test-did-finder
    uses: ./.github/workflows/deployments/deploy-did-finder-python.yaml

  call-test-servicex-app:
    uses: ./.github/workflows/tests/test-servicex-app.yaml
  call-deploy-servicex-app:
    needs: call-test-servicex-app
    uses: ./.github/workflows/deployments/deploy-servicex-app.yaml