name: CI/CD

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set_matrix
        run: |
          pwd
          JSON=$(cat deploy-config.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  test-servicex:
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7 ]
        app: ${{fromJson(needs.job1.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r requirements_dev.txt
          pip list
        working-directory: ${{ matrix.app.dir_name }}
      - name: Lint with Flake8
        working-directory: ${{ matrix.app.dir_name }}
        run: |
          flake8
      - name: Test with pytest
        working-directory: ${{ matrix.app.dir_name }}
        run: |
          python -m coverage run -m pytest -r sx
      - name: Report coverage with Codecov
        working-directory: ${{ matrix.app.dir_name }}
        run: |
          codecov --token=${{ secrets.CODECOV_TOKEN }}

  publish-servicex:
    needs: test-servicex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract tag name
        working-directory: ${{ matrix.app.dir_name }}
        shell: bash
        run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
        id: extract_tag_name

      - name: Build Uproot Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          context: ${{ matrix.app.dir_name }}
          name: sslhep/${{ matrix.app.image_name }}:${{ steps.extract_tag_name.outputs.imagetag }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#  call-test-code-gen-python:
#    strategy:
#      matrix:
#        app-version: [ "app", "did-finder"]
#    uses: ./.github/workflows/test-code-gen-python.yaml
#  call-deploy-code-gen:
#    needs: call-test-did-finder
#    uses: ./.github/workflows/deploy-code-gen-python.yaml
#    secrets:
#      username: ${{ secrets.DOCKER_USERNAME }}
#      password: ${{ secrets.DOCKER_PASSWORD }}
#  call-test-servicex-app:
#    uses: ./.github/workflows/test-servicex-app.yaml
#  call-deploy-servicex-app:
#    needs: call-test-servicex-app
#    uses: ./.github/workflows/deploy-servicex-app.yaml
#    secrets:
#      username: ${{ secrets.DOCKER_USERNAME }}
#      password: ${{ secrets.DOCKER_PASSWORD }}