name: Helm Release Workflow (Workflow Dispatch)

on:
  release:

jobs:
#  call-test-and-publish-workflow:
#    name: Run Tests on Helm
#    uses: .github/workflows/ci_helm.yml

  release-helm:
#    needs: call-test-and-publish-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Create release version env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - name: Create helm package
        working-directory: ./helm
        run: |
          mkdir release-package
          sed -e "s/appVersion: .*$/appVersion: $RELEASE_VERSION/" -e "s/version: .*$/version: $RELEASE_VERSION/" servicex/Chart.yaml 
          sed -E -e "s/  tag:\s*[[:digit:]]{8}-[[:digit:]]{4}-stable.*$/  tag: $RELEASE_VERSION/" -e "s/  defaultTransformerTag:\s*.+$/  defaultTransformerTag: $RELEASE_VERSION/" servicex/values.yaml
          cat servicex/Chart.yaml 
          cat servicex/values.yaml
          helm dependency update servicex
          helm package servicex --destination release-package
          helm repo index release-package --url https://ssl-hep.github.io/ssl-helm-charts/
          pwd

      - name: Pull ssl-helm-charts
        uses: actions/checkout@master
        with:
          name: prajwalkkumar/ssl-helm-charts
          ref: refs/heads/gh-pages
      - uses: actions/checkout@master

      - name: Move the package
        run: |
          mv release-package ssl-helm-charts/
          ls

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './helm/release-package'
          destination-github-username: 'prajwalkkumar'
          destination-repository-name: 'ssl-helm-charts'
          target-branch: 'master'
