name: DEPLOY-DID-FINDER-PYTHON

on:
  workflow_call:
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  publish-did-finder-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Extract tag name
      working-directory: ./servicex_code_gen_python
      shell: bash
      run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag_name

    - name: Build Uproot Image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        context: ./servicex_code_gen_python
        name: sslhep/servicex_code_gen_python:${{ steps.extract_tag_name.outputs.imagetag }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}