on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull flux_river_configs
        uses: actions/checkout@master
        with:
          repository: prajwalkkumar/flux_river_configs
          ref: main
          path: flux_river_configs
      - name: Pull ssl-helm-charts
        uses: actions/checkout@master
        with:
          repository: prajwalkkumar/ssl-helm-charts
          ref: master
          path: ssl-helm-charts
      - name: Create release version env var
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
      - name: Create helm package
        working-directory: ./helm
        run: |
          pwd
          mkdir release-package
          python3 ../.github/workflows/update_versions.py $RELEASE_VERSION
          cat servicex/Chart.yaml
          cat servicex/values.yaml
          helm dependency update servicex
          helm package servicex --destination release-package
          helm repo index release-package --url https://ssl-hep.github.io/ssl-helm-charts/
          mv release-package/* ../ssl-helm-charts/
#      - name: Move the package
#        working-directory: ./helm
#        run: |
#          mv release-package ../ssl-helm-charts/
      - name: Pushes to ssl-helm-packages repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'ssl-helm-charts'
          destination-github-username: 'prajwalkkumar'
          destination-repository-name: 'ssl-helm-charts'
          target-branch: 'master'
      - name: Pushes to flux-river-configs repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'flux_river_configs'
          destination-github-username: 'prajwalkkumar'
          destination-repository-name: 'flux_river_configs'
          target-branch: 'main'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false